### ISSUE TITLE
roboRIO image / WPILib update required

### ISSUE THREAD

**Issue by sciencewhiz** [Team3128/3128-robot-2022#62]
I noticed that your code is using WPILib 2022.2.1. Per team update 8, the roboRIO image is required to be 2022_v4.0, which requires an update to WPILib 2022.3.1. The FRC Game Tools update that includes the new image is available at https://www.ni.com/en-us/support/downloads/drivers/download.frc-game-tools.html#440024. The WPILib 2022.3.1 update is available at https://github.com/wpilibsuite/allwpilib/releases

**Comment by jude-lif** [comment]
This is fixed now. Thanks for pointing it out.
